package com.boongtol.umtp_android.network

data class ResaleTradeAfterPurchaseUpsertRequest(
    val user_id: String,
    val source: String = "joongna",
    val product_id: String? = null,
    val url: String? = null,
    val updates: Map<String, Any?> = emptyMap(),
)

data class ResaleTradeAfterResaleUpsertRequest(
    val user_id: String,
    val source: String = "joongna",
    val product_id: String? = null,
    val url: String? = null,
    val updates: Map<String, Any?> = emptyMap(),
)

data class ResaleTradeJourneyFromProductRequest(
    val source: String,
    val product_id: String,
)

data class TradeJourneyStartFromUrlRequest(
    val user_id: String,
    val url: String,
)

data class TradeJourneyStartFromAlertRequest(
    val user_id: String,
    val alert_event_id: Long,
)

data class TradeJourneyStartFromReadArchiveRequest(
    val user_id: String,
    val read_archive_event_id: Long,
)

data class ResaleTradeJourneyPatchRequest(
    val updates: Map<String, Any?> = emptyMap(),
)

data class ResaleTradeJourneyDeleteSelectedRequest(
    val journey_ids: List<Long> = emptyList(),
)

data class ResaleTradeJourneyDeleteResponse(
    val ok: Boolean,
    val deleted_count: Int? = null,
    val reason: String? = null,
    val message: String? = null,
)

data class ResaleTradeJourneyListResponse(
    val ok: Boolean,
    val items: List<ResaleTradeJourneyRow> = emptyList(),
    val reason: String? = null,
    val message: String? = null,
)

data class ResaleTradeJourneyResponse(
    val ok: Boolean,
    val id: Long? = null,
    val source: String? = null,
    val product_id: String? = null,
    val current_stage: String? = null,
    val row: ResaleTradeJourneyRow? = null,
    val reason: String? = null,
    val message: String? = null,
)

data class TradeJourneyStartResponse(
    val ok: Boolean,
    val existing: Boolean? = null,
    val trade_journey_id: Long? = null,
    val id: Long? = null,
    val source: String? = null,
    val product_id: String? = null,
    val current_stage: String? = null,
    val row: ResaleTradeJourneyRow? = null,
    val reason: String? = null,
    val message: String? = null,
)

data class ResaleTradeJourneyRow(
    val id: Long? = null,
    val user_id: String? = null,
    val source: String? = null,
    val product_id: String? = null,
    val url: String? = null,
    val url_digest: String? = null,
    val title: String? = null,
    val listing_created_at: String? = null,
    val discovered_at: String? = null,
    val listing_price_krw: Int? = null,
    val seller_location: String? = null,
    val image_urls: Any? = null,
    val body_text: String? = null,
    val fair_price_krw: Int? = null,
    val discount_rate_percent: Double? = null,
    val expected_profit_krw: Int? = null,
    val risk_score: Int? = null,
    val reason_tags: Any? = null,
    val product_type: String? = null,
    val chip: String? = null,
    val screen_inch: Int? = null,
    val ram_gb: Int? = null,
    val ssd_gb: Int? = null,
    val color: String? = null,
    val keyboard_layout: String? = null,
    val seller_nickname: String? = null,
    val seller_shop_id: String? = null,
    val contacted_at: String? = null,
    val seller_response_at: String? = null,
    val contact_record: String? = null,
    val conversation_text: String? = null,
    val purchase_contact_record: String? = null,
    val purchase_conversation_text: String? = null,
    val response_time_minutes: Int? = null,
    val seller_answer_text: String? = null,
    val negotiable: Any? = null,
    val seller_tone: String? = null,
    val suspicious_points: Any? = null,
    val confirmed_price_krw: Int? = null,
    val decision_at: String? = null,
    val decision_result: String? = null,
    val decision_reason: String? = null,
    val target_purchase_price_krw: Int? = null,
    val expected_sale_price_krw: Int? = null,
    val expected_net_profit_krw: Int? = null,
    val expected_sale_duration_days: Int? = null,
    val current_stage: String? = null,
    val purchased_at: String? = null,
    val purchase_price_krw: Int? = null,
    val purchase_method: String? = null,
    val purchase_location: String? = null,
    val transport_cost_krw: Int? = null,
    val shipping_cost_krw: Int? = null,
    val total_cost_krw: Int? = null,
    val payment_method: String? = null,
    val money_sent_at: String? = null,
    val money_received_at: String? = null,
    val account_number: String? = null,
    val purchase_account_number: String? = null,
    val serial_number: String? = null,
    val model_number: String? = null,
    val applecare_status: String? = null,
    val activation_lock_off: Any? = null,
    val mdm_lock_none: Any? = null,
    val cpu_core_count: Int? = null,
    val gpu_core_count: Int? = null,
    val battery_health_percent: Int? = null,
    val battery_cycle_count: Int? = null,
    val battery_condition: String? = null,
    val truetone_ok: Any? = null,
    val display_condition: String? = null,
    val keyboard_condition: String? = null,
    val trackpad_condition: String? = null,
    val speaker_condition: String? = null,
    val camera_condition: String? = null,
    val wifi_bluetooth_ok: Any? = null,
    val exterior_grade: String? = null,
    val included_items: Any? = null,
    val repair_suspected: Any? = null,
    val inspection_notes: String? = null,
    val cleaned_at: String? = null,
    val photo_taken_at: String? = null,
    val resale_title: String? = null,
    val resale_body_text: String? = null,
    val resale_photo_count: Int? = null,
    val resale_listing_price_krw: Int? = null,
    val minimum_accept_price_krw: Int? = null,
    val resale_platform: String? = null,
    val resale_strategy_notes: String? = null,
    val resale_listing_created_at: String? = null,
    val resale_url: String? = null,
    val resale_product_id: String? = null,
    val initial_resale_price_krw: Int? = null,
    val upload_time_slot: String? = null,
    val view_count: Int? = null,
    val favorite_count: Int? = null,
    val inquiry_count: Int? = null,
    val first_inquiry_at: String? = null,
    val first_inquiry_delay_minutes: Int? = null,
    val negotiation_count: Int? = null,
    val price_drop_count: Int? = null,
    val price_drop_history: Any? = null,
    val buyer_questions: Any? = null,
    val common_objections: Any? = null,
    val resale_contact_record: String? = null,
    val resale_conversation_text: String? = null,
    val resale_account_number: String? = null,
    val sold_at: String? = null,
    val sale_price_krw: Int? = null,
    val buyer_nickname: String? = null,
    val sale_method: String? = null,
    val sale_location: String? = null,
    val sale_platform: String? = null,
    val final_shipping_cost_krw: Int? = null,
    val platform_fee_krw: Int? = null,
    val refund_or_claim: String? = null,
    val gross_profit_krw: Int? = null,
    val net_profit_krw: Int? = null,
    val roi_percent: Double? = null,
    val purchase_speed_minutes: Int? = null,
    val sale_duration_hours: Int? = null,
    val total_holding_time_hours: Int? = null,
    val profit_per_day_krw: Int? = null,
    val final_result_notes: String? = null,
    val created_at: String? = null,
    val updated_at: String? = null,
)

data class ResaleTradeUpsertResponse(
    val ok: Boolean,
    val id: Long? = null,
    val source: String? = null,
    val product_id: String? = null,
    val current_stage: String? = null,
    val row: ResaleTradeJourneyRow? = null,
    val reason: String? = null,
    val message: String? = null,
)
