USE UMTP_RB;

ALTER TABLE user_fair_prices
  ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE AFTER alert_drop_rate_percent,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

UPDATE user_fair_prices
SET enabled = TRUE
WHERE enabled IS NULL;
