USE UMTP_RB;

CREATE TABLE IF NOT EXISTS joongna_seen_products (
  seq BIGINT UNSIGNED NOT NULL,
  search_word VARCHAR(255) NOT NULL,
  title VARCHAR(255) NULL,
  price INT NULL,
  product_url VARCHAR(1000) NOT NULL,
  image_url VARCHAR(1000) NULL,
  sort_date VARCHAR(100) NULL,
  first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_analyzed_at TIMESTAMP NULL,
  seen_count INT NOT NULL DEFAULT 1,
  last_title VARCHAR(500) NULL,
  last_price_krw INT NULL,
  last_status VARCHAR(50) NULL,
  last_refresh_key VARCHAR(255) NULL,
  last_sort_date DATETIME NULL,
  previous_sort_date DATETIME NULL,
  sort_date_changed_count INT NOT NULL DEFAULT 0,
  last_sort_date_changed_at TIMESTAMP NULL,
  last_change_reason VARCHAR(255) NULL,
  last_body_hash VARCHAR(64) NULL,
  last_self_check_hash VARCHAR(64) NULL,
  last_content_revision_hash VARCHAR(64) NULL,
  last_content_checked_at TIMESTAMP NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (seq),
  KEY idx_search_word_first_seen_at (search_word, first_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
