USE UMTP_RB;

CREATE TABLE IF NOT EXISTS alert_read_archive_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(100) NOT NULL,
  alert_event_id BIGINT UNSIGNED NULL,
  action_type VARCHAR(50) NOT NULL,
  requested_count INT NULL,
  affected_count INT NULL,
  skipped_count INT NULL,
  not_found_ids_json TEXT NULL,
  reason VARCHAR(100) NULL,
  metadata_json LONGTEXT NULL,
  alert_trigger_reason VARCHAR(100) NULL,
  alert_condition_label VARCHAR(100) NULL,
  alert_source VARCHAR(50) NULL,
  alert_url TEXT NULL,
  alert_listing_image_url TEXT NULL,
  alert_title VARCHAR(500) NULL,
  alert_product_id VARCHAR(100) NULL,
  alert_sort_date DATETIME NULL,
  alert_product_type VARCHAR(100) NULL,
  alert_chip VARCHAR(50) NULL,
  alert_screen_inch INT NULL,
  alert_ram_gb INT NULL,
  alert_ssd_gb INT NULL,
  alert_price_krw INT NULL,
  alert_fair_price_krw INT NULL,
  alert_target_price_krw INT NULL,
  alert_drop_rate_percent DECIMAL(10,2) NULL,
  alert_rule_drop_rate_percent DECIMAL(10,2) NULL,
  alert_price_direction VARCHAR(32) NULL,
  alert_risk_level VARCHAR(20) NULL,
  alert_risk_label VARCHAR(20) NULL,
  alert_risk_score INT NULL,
  alert_risk_keywords TEXT NULL,
  alert_trade_type VARCHAR(20) NULL,
  alert_is_exchange_post TINYINT(1) NULL,
  alert_trade_flags_text VARCHAR(100) NULL,
  alert_special_notes_text TEXT NULL,
  alert_body_excerpt TEXT NULL,
  alert_body_text LONGTEXT NULL,
  alert_message TEXT NULL,
  alert_status VARCHAR(30) NULL,
  alert_analyzed_at DATETIME NULL,
  alert_created_at DATETIME NULL,
  alert_sent_at DATETIME NULL,
  alert_updated_at DATETIME NULL,
  alert_read_at DATETIME NULL,
  alert_payload_json LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_alert_read_archive_events_user_created_at (user_id, created_at),
  KEY idx_alert_read_archive_events_action_created_at (action_type, created_at),
  KEY idx_alert_read_archive_events_alert_event_id (alert_event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
